### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by bluesky0811** [mklimek/FrameVideoView#4]
java.lang.NoClassDefFoundError: org.slf4j.LoggerFactory
            at mateuszklimek.framevideoview.FrameVideoView.<clinit>(FrameVideoView.java:26)
            at com.papelook.favor.view.advertise.VideoAdvertise.init(VideoAdvertise.java:62)
            at com.papelook.favor.view.advertise.VideoAdvertise.setAdvertise(VideoAdvertise.java:96)
            at com.papelook.favor.ui.fragment.WriterArticleListFragment$GetAdvertiseTask.onPostExecute(WriterArticleListFragment.java:396)
            at com.papelook.favor.ui.fragment.WriterArticleListFragment$GetAdvertiseTask.onPostExecute(WriterArticleListFragment.java:321)
            at android.os.AsyncTask.finish(AsyncTask.java:632)
            at android.os.AsyncTask.access$600(AsyncTask.java:177)
            at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:157)
            at android.app.ActivityThread.main(ActivityThread.java:5356)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by mklimek** [comment]
I use [slf4android](https://github.com/bright/slf4android) for logging.
Add it to `build.gradle` or replace log lines with standard android 'Log' class.

**Comment by dylanreid** [comment]
I ran into this also, I'm guessing because @bluesky0811 copied this into his gradle file:

dependencies {
    compile('mateuszklimek.framevideoview:framevideoview:1.1.1@aar')
    //other dependencies
}

If you remove the "@aar" portion of the dependency, you will get the referenced library and it should compile fine. Hope that helps.
